name: check WPCS

on: [ push, pull_request ]

jobs:
  cs_and_tests:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php-version: [ '7.4', '8.0', '8.1', '8.2' ]
    env:
      wp-directory: wordpress
      wp-plugin-directory: wordpress/wp-content/plugins/thumbnify

    runs-on: ${{ matrix.os }}

    name: PHP ${{ matrix.php-version }} on ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: ${{ env.wp-plugin-directory }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: json, mysqli, mbstring, zip

      - name: Install dependencies with caching
        uses: ramsey/composer-install@v2
        with:
          working-directory: ${{ env.wp-plugin-directory }}

      - name: Run code sniffer
        working-directory: ${{ env.wp-plugin-directory }}
        run: composer phpcs
